// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWM_Ot9xm1Q-PIUCOMRQ5qEDQGOLTpK_M',
    appId: '1:995357910311:web:3f78488d6e62b532ea7502',
    messagingSenderId: '995357910311',
    projectId: 'toktok-44902',
    authDomain: 'toktok-44902.firebaseapp.com',
    storageBucket: 'toktok-44902.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_GavcRbfYq-TN7g8_TTujMZYo-Tg3tb8',
    appId: '1:995357910311:android:19dbcdba2fe47efeea7502',
    messagingSenderId: '995357910311',
    projectId: 'toktok-44902',
    storageBucket: 'toktok-44902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpy3YCZsr_yFWyvU4B3sevCuXsGiWEJRA',
    appId: '1:995357910311:ios:e35068f56cf68128ea7502',
    messagingSenderId: '995357910311',
    projectId: 'toktok-44902',
    storageBucket: 'toktok-44902.appspot.com',
    iosClientId: '995357910311-5iefr3f5jt5sa1vc4cbohq45a4pkfn5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokTokApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpy3YCZsr_yFWyvU4B3sevCuXsGiWEJRA',
    appId: '1:995357910311:ios:e35068f56cf68128ea7502',
    messagingSenderId: '995357910311',
    projectId: 'toktok-44902',
    storageBucket: 'toktok-44902.appspot.com',
    iosClientId: '995357910311-5iefr3f5jt5sa1vc4cbohq45a4pkfn5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokTokApp',
  );
}
